/** ポップで親しみやすい共通テーマ（Mobile） */
export const theme = {
  bg: '#fff8f0',
  bgSoft: '#fff1f2',
  surface: '#ffffff',
  ink: '#3f2f2a',
  inkMuted: '#78716c',
  primary: '#f97316',
  primaryDark: '#ea580c',
  primarySoft: '#ffedd5',
  sky: '#38bdf8',
  skySoft: '#e0f2fe',
  pink: '#f472b6',
  pinkSoft: '#fce7f3',
  mint: '#34d399',
  mintSoft: '#d1fae5',
  lavender: '#c084fc',
  lavenderSoft: '#f3e8ff',
  yellow: '#fbbf24',
  yellowSoft: '#fef9c3',
  border: '#fed7aa',
  borderSky: '#bae6fd',
  borderLavender: '#d8b4fe',
  shadow: {
    card: {
      shadowColor: '#f97316',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 4,
    },
  },
} as const;

export const pop = {
  screen: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  centered: {
    flex: 1,
    backgroundColor: theme.bg,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  scroll: {
    padding: 20,
    paddingBottom: 40,
    backgroundColor: theme.bg,
    gap: 14,
  },
  eyebrow: {
    letterSpacing: 3,
    color: theme.primary,
    fontSize: 11,
    fontWeight: '800' as const,
    textTransform: 'uppercase' as const,
  },
  title: {
    marginTop: 4,
    color: theme.ink,
    fontSize: 24,
    fontWeight: '800' as const,
  },
  muted: {
    color: theme.inkMuted,
    fontSize: 13,
  },
  card: {
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.border,
    padding: 16,
    backgroundColor: theme.surface,
    gap: 6,
    ...theme.shadow.card,
  },
  cardSky: {
    borderColor: theme.borderSky,
    backgroundColor: theme.skySoft,
  },
  cardLavender: {
    borderColor: theme.borderLavender,
    backgroundColor: theme.lavenderSoft,
  },
  input: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    paddingHorizontal: 14,
    fontSize: 16,
    color: theme.ink,
  },
  btnPrimary: {
    marginTop: 20,
    backgroundColor: theme.primary,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center' as const,
    ...theme.shadow.card,
  },
  btnPrimaryLabel: {
    color: '#fff',
    fontWeight: '800' as const,
    fontSize: 16,
  },
  navLink: {
    color: theme.primary,
    fontWeight: '700' as const,
    fontSize: 14,
  },
};
